query Analytics($filter: AnalyticsFilter) {
  analytics {
    series(filter: $filter)  {
      period
      rows {
        dimensions {
          path
        }
        value        
      }
    }
  }
}