query Analytics($filter: AnalyticsFilter) {
  analytics(filter: $filter) {
    series {
      period
      rows {
        dimensions {
          path
        }
        value        
      }
    }
  }
}